### ISSUE TITLE
如何才能自定义表头

### ISSUE THREAD

**Issue by liuajingliu** [alibaba/ali-react-table#100]
目前处于探索调研ali-react-table阶段，我想对表头进行自定义，遇到了#38 相同的问题，但是我发现当初给的解决方案 import { transformColumn, applyTransforms } from 'ali-react-table/biz' 中的transformColumn已经没办法引入了，请问现在该如何解决？

**Comment by shinima** [comment]
现在的 API 引入方式为：   `import { traverseColumn } from 'ali-react-table'`

因为表头单元格的 props 是在 每一列的 `column.headerCellProps` 中被定义的，所以你可以预先处理好所有的 column，然后传给表格组件就可以了。  不一定要用到 traverseColumn 这个 API 的。

举个例子：
```typescript
[
  {
    code: "provinceName",
    name: "省份",
    width: 150,
    headerCellProps: {
      style: { color: "white", fontSize: 20, background: "#1ea7fd" },
    },
  },
  // ... other columns
  {
    code: "updateTime",
    name: "最后更新时间",
    width: 180,
    headerCellProps: {
      style: {
        letterSpacing: 10,
        fontSize: 20,
        fontWeight: "bold",
        textAlign: "center",
      },
    },
  },
];
```

就可以得到这样的效果：

![image](https://user-images.githubusercontent.com/5550931/100131181-ad3c3480-2ebe-11eb-825d-df99b5dfae6c.png)
