### ISSUE TITLE
当数据达到千条以上时，开启checkbox的时候，勾选响应很慢，这个有方案优化么？

### ISSUE THREAD

**Issue by rudyzou** [alibaba/ali-react-table#101]
当数据达到千条以上时，开启checkbox的时候，勾选响应很慢，这个有方案优化么？

**Comment by shinima** [comment]
我去本地测试下。   或者你能帮忙看一下哪一部分比较好使么？

**Comment by shinima** [comment]
试了一下，几千条数据的多选并不卡，你看下是不是页面上其他组件导致的

![屏幕录制2020-11-27 13 28 37](https://user-images.githubusercontent.com/5550931/100414755-72e8b800-30b5-11eb-9dc7-a0358329852e.gif)

**Comment by rudyzou** [comment]
> 试了一下，几千条数据的多选并不卡，你看下是不是页面上其他组件导致的
> 
> ![屏幕录制2020-11-27 13 28 37](https://user-images.githubusercontent.com/5550931/100414755-72e8b800-30b5-11eb-9dc7-a0358329852e.gif)

感谢，是上层页面影响了。
