### ISSUE TITLE
pipeline 支持merge操作么

### ISSUE THREAD

**Issue by liuajingliu** [alibaba/ali-react-table#102]
想基于ali-react-table封装一个公共组件，可以抽离一些公共的pipeline属性，但在业务组件中可能有一些独有的自定义的pipeline，请问pipeline可以进行merge操作么，业务组件和公共组件merge后传到最终的BaseTable里面

**Comment by shinima** [comment]
你可以定义自己的表格拓展，使用的时候调用 `pipeline.use(...)` 就可以了。

```
pipeline
  .use(features.multiSelect(...))
  .use(youOwnFeature)
  .use(someFeatureFromNpmPackage)
```
