### ISSUE TITLE
能锁定行在底部么？

### ISSUE THREAD

**Issue by daguanjia** [alibaba/ali-react-table#104]
类似总计固定在表格底部的功能，我现在是外层又搞了个table去定位，是否考虑暴露一个自定义tfoot?

**Comment by shinima** [comment]
嗯，这个我本地试过是没问题的。目前这个可以暂时按[这个示例](https://ali-react-table.js.org/examples/table?example=%E8%A1%A8%E6%A0%BC%E5%90%B8%E5%BA%95) 来实现自定义的 tfoot
