### ISSUE TITLE
「自适应列宽」这个功能可以支持到 pipeline 里吗，感谢 🤝

### ISSUE THREAD

**Issue by sunwenli** [alibaba/ali-react-table#107]

**Comment by shinima** [comment]
> useAutoWidthTransform 会在 didMount/didUpdate 中获取单元格的实际内容宽度，然后重新设置表格列宽，实现「自适应列宽」。
> useAutoWidthTransform 会频繁地从 DOM 中获取单元格的实际渲染宽度，单元格数量较多时会导致性能问题。 useAutoWidthTransform 不兼容「拖拽调整列宽」，不兼容「横向虚拟滚动」，不兼容存在 colSpan 的情况。谨慎使用，这里只提供 demo。

「自适应列宽」的问题太多了，不考虑支持这个功能。
