### ISSUE TITLE
建议将 react 放到 peerDependencies 里

### ISSUE THREAD

**Issue by ycjcl868** [alibaba/ali-react-table#111]
这样直接给项目安装了 react 17，，，

![image](https://user-images.githubusercontent.com/13595509/101864633-1eb7ec00-3b29-11eb-9db9-d5a2fa9f6f58.png)

**Comment by shinima** [comment]
![image](https://user-images.githubusercontent.com/5550931/101867431-1ce83a00-3bb6-11eb-880f-1bc647efbe23.png)

现在是这么书写依赖的版本号的，我看看有没有什么更好的书写方式

**Comment by shinima** [comment]
已更新，安装 `^2.2.1` 版本就可以了
