### ISSUE TITLE
CrossTable如何吸顶呢？

### ISSUE THREAD

**Issue by kindofcat** [alibaba/ali-react-table#113]
CrossTable如何吸顶呢？

**Comment by shinima** [comment]
CrossTable 自带表头吸顶的

可以参考[这个示例](https://ali-react-table.js.org/examples/others/simple-pivot-table/)，相应的代码：

https://github.com/alibaba/ali-react-table/blob/a0703b140eb0de4b410a25c37e5659c3e0ca342e/packages/website/examples/others/simple-pivot-table.stories.tsx#L155-L179

**Comment by kindofcat** [comment]
但是我引入antd和antd pro 它没有效果

**Comment by shinima** [comment]
外层样式导致 sticky position 无效，这个是 antd pro 外框架的问题

可以参考下这个  https://github.com/alibaba/ali-react-table/issues/83#issuecomment-712559690
