### ISSUE TITLE
是否有实现底部合计的方法？

### ISSUE THREAD

**Issue by gitlwz** [alibaba/ali-react-table#115]
在底部进行一些统计、合计功能有什么方法可以实现吗？

**Comment by shinima** [comment]
看下这个示例能否满足你的需求？
https://ali-react-table.js.org/examples/table?example=%E8%A1%A8%E6%A0%BC%E5%90%B8%E5%BA%95

**Comment by daguanjia** [comment]
> 看下这个示例能否满足你的需求？
> https://ali-react-table.js.org/examples/table?example=%E8%A1%A8%E6%A0%BC%E5%90%B8%E5%BA%95

我横向滚动或者锁列 底部合计也一起实现 这个列子不满足我的需求

**Comment by shinima** [comment]
> 我横向滚动或者锁列 底部合计也一起实现 这个列子不满足我的需求

这个目前还没有。  本地我有试过，类似的效果是可以实现的，不过正式加到表格组件内部可能要等一段时间。
