### ISSUE TITLE
convertDrillTreeToCrossTree 可以自定义维度的排序吗？

### ISSUE THREAD

**Issue by kevinpursuing** [alibaba/ali-react-table#119]
比如按激活日期进行分类，可以按照从早到晚排吗

第二个问题是，透视表可以支持排序吗？

**Comment by shinima** [comment]
「比如按激活日期进行分类，可以按照从早到晚排吗」   这个你直接对 drillTree 进行排序就好了

「透视表可以支持排序」 暂时不提供这个功能，不过这个可以在上层进行拓展

**Comment by kevinpursuing** [comment]
> 「比如按激活日期进行分类，可以按照从早到晚排吗」 这个你直接对 drillTree 进行排序就好了
> 
> 「透视表可以支持排序」 暂时不提供这个功能，不过这个可以在上层进行拓展

就是说用buildDrillTree处理完后自行在做一次排序处理是吗？

**Comment by shinima** [comment]
> 就是说用buildDrillTree处理完后自行在做一次排序处理是吗？

对的
