### ISSUE TITLE
现在可以实现伸缩列么

### ISSUE THREAD

**Issue by daguanjia** [alibaba/ali-react-table#123]

**Comment by shinima** [comment]
伸缩列具体表现是什么样的，能简单描述下么？

**Comment by daguanjia** [comment]
> 伸缩列具体表现是什么样的，能简单描述下么？

就是类似利用react-resizable  表头的宽度可以手动调整

**Comment by shinima** [comment]
原来 v1 版本是有的 😅  ，不过伸缩列小问题比较多，在我们内部也算不上高频需求，所以就被我干掉了

**Comment by daguanjia** [comment]
> 原来 v1 版本是有的 😅 ，不过伸缩列小问题比较多，在我们内部也算不上高频需求，所以就被我干掉了

好的 大佬 ，你们的表格已经很好用了，还是抵不过我们的产品 =。=

**Comment by shinima** [comment]
感谢支持。   伸缩列短期内不再提供了，issue 先关了。

**Comment by cschensai** [comment]
伸缩列这个还能支持下吗？大佬

**Comment by maxborts** [comment]
我们也有这个需求 - -

**Comment by shinima** [comment]
@maxborts  看下这个呢   https://ali-react-table.js.org/docs/pipeline/features/column-resize/
