### ISSUE TITLE
行展开+固定列+横向虚拟加载 显示有问题

### ISSUE THREAD

**Issue by zhiaiing** [alibaba/ali-react-table#127]
行展开+固定列+横向虚拟加载  展开行的宽度 不对

具体看 
https://codesandbox.io/s/ali-react-table-xingzhankaigudinglie-7mly4?file=/index.js
横向滚动到最右侧

**Comment by shinima** [comment]
因为 锁列部分和非锁列的部分不支持合并在一起，但 rowGrouping 会使得一整行的单元格都合并起来，所以 rowGrouping 和固定列 目前还不能一起使用。

**Comment by shinima** [comment]
目前「行展开+固定列」这种暂不支持，issue 先关了
