### ISSUE TITLE
拖动横向滚动条时，table 纵向内容区闪烁

### ISSUE THREAD

**Issue by zhiaiing** [alibaba/ali-react-table#133]
![Kapture 2021-01-21 at 18 06 35](https://user-images.githubusercontent.com/15857315/105336847-aad32e00-5c14-11eb-9f52-15ca63e18c01.gif)

http://chuantu.xyz/t6/741/1611224123x1700340467.gif

table columns  有某列高度比较高,  拖动时就可能出现这种情况

**Comment by shinima** [comment]
这个情况是正常的，虚拟滚动就是不渲染 viewport 之外的单元格

**Comment by zhiaiing** [comment]
拖动时 闪烁 时正常， 问题是 松开鼠标还是这样， 一直再闪

**Comment by shinima** [comment]
那应该是表格组件在一些边界情况下 处理有问题

@zhiaiing  能提供一些复现的例子么，可以参考下这个   https://codesandbox.io/s/ali-react-table-online-demo-w2wte?file=/index.js

**Comment by zhiaiing** [comment]
https://codesandbox.io/s/ali-react-table-online-demo-forked-kpfof?file=/index.js:1874-1882

windows电脑好重现,  mac要慢慢拖 比较难重现。

**Comment by shinima** [comment]
@zhiaiing 在 windows 电脑上比较好复现

问题出现的原因应该是…

1. 横向滚动 触发虚拟滚动重新渲染， 渲染高度较大的列
2. 表格高度超过预设高度，右侧出现滚动条
3. 表格可渲染范围变小，div.art-table 尺寸变小
4. ResizeObservable 回调函数被触发，表格准备重新渲染
5. 因为此时可渲染范围变小了，导致虚拟滚动计算时 判断高度较大的列 不需要展示
6. 高度较大的列被隐藏，右侧滚动条消失
7. ResizeObservable 回调函数被触发，表格重新渲染
8. 因为此时可渲染范围变大了，导致虚拟滚动计算时 判断高度较大的列 需要展示
9. 回到 2，发生抖动

怎么处理我再想想，这个处理起来还比较麻烦

**Comment by shinima** [comment]
想了想这个问题目前无解，先在上层代码中指定下样式吧。
