### ISSUE TITLE
为啥不支持表格输入框编辑

### ISSUE THREAD

**Issue by chengdick** [alibaba/ali-react-table#134]
为啥不支持表格输入框编辑

**Comment by shinima** [comment]
1. 编辑功能较为灵活，作为表格组件而言 比较难定义一个通用的 API
2. ali-react-table 没有绑定组件库，也不打算提供与具体组件绑定的功能
3. 个人精力有限，然后这个功能在上层拓展并不困难，推荐根据自己的需求进行封装

**Comment by chengdick** [comment]
好的，谢谢您的回答



在 2021-01-22 11:31:27，"肥超" ***@***.***> 写道：

编辑功能较为灵活，作为表格组件而言 比较难定义一个通用的 API
ali-react-table 没有绑定组件库，也不打算提供与具体组件绑定的功能
个人精力有限，然后这个功能在上层拓展并不困难，推荐根据自己的需求进行封装
