### ISSUE TITLE
支持排行榜表格

### ISSUE THREAD

**Issue by melin** [alibaba/ali-react-table#137]
这个是quickbi 效果，能够支持？ 表格每行有一个进度条，不显示border颜色：
![image](https://user-images.githubusercontent.com/1145830/105952205-37b23780-60ac-11eb-8d4f-9ba34400d806.png)

**Comment by shinima** [comment]
这个自定义一下单元格渲染方式就可以实现了

这里也有一个简单的例子  https://ali-react-table.js.org/examples/biz/rank-table
