### ISSUE TITLE
有计划支持表格列宽度拖动？

### ISSUE THREAD

**Issue by melin** [alibaba/ali-react-table#138]

**Comment by shinima** [comment]
原先支持过，v2 版本去掉了。这里有个原先的例子可以看下 https://ali-react-table.js.org/v1/?path=/story/%E8%A1%A8%E6%A0%BC-%E5%B8%B8%E7%94%A8%E5%8A%9F%E8%83%BD%E7%A4%BA%E4%BE%8B--%E6%8B%96%E6%8B%BD%E8%B0%83%E6%95%B4%E5%88%97%E5%AE%BD

---

拖拽交互和 React 的实现方式并不匹配：
* 拖拽会用到大量 DOM api，需要精确控制每一列的宽度
* 而用 react + html table 标签去实现表格组件是为了…
  1. 不关心具体 DOM，而是使用声明式的方式快速渲染想要的表格
  2. 不精确控制列宽，而是让浏览器自动去进行布局

两者的出发点不同，所以后面估计 ali-react-table 也不会提供这个功能。需要拖拽的话，比较推荐类 excel 的表格组件，或是 ant design 组件库自带的表格组件。

**Comment by melin** [comment]
需要ali-react-table 强大功能，再加上列宽拖动，缺少列宽拖动表格好像少了点什么，毕竟 react + html table 只有基本功能。告知用户开启列宽拖动有性能，展现数据不多的情况，性能在可接收的范围。建议v2版本保留列宽拖动。

**Comment by shinima** [comment]
在考虑中了，不过最近比较忙（临近阿里财年底绩效考核），可能要过一段时间才有空来处理

**Comment by melin** [comment]
> 在考虑中了，不过最近比较忙（临近阿里财年底绩效考核），可能要过一段时间才有空来处理

最近有时间支持吗？
