### ISSUE TITLE
实现可视窗口底部的滚动条

### ISSUE THREAD

**Issue by StylishSite** [alibaba/ali-react-table#139]
你好，我想请教一下如何实现能固定在底部的滚动条吗？因为表格数据过多的时候，要一直拉到底部才可以向右侧拉动，所以想请教一下可否实现此功能

**Comment by shinima** [comment]
这个功能现在表格组件默认就自带了的

**Comment by StylishSite** [comment]
> 这个功能现在表格组件默认就自带了的

是指这个stickBottom属性吗，这个是针对当前表格所在父盒子的吧，不是针对可视区

**Comment by shinima** [comment]
不是很明白你指的具体是哪种，可以给个截图看一下么

---

这个是目前表格自带的滚动条

![Uploading 屏幕录制2021-02-02 13.55.47.gif…]()

**Comment by StylishSite** [comment]
![image](https://user-images.githubusercontent.com/59858493/106577210-0dafb800-6579-11eb-8c37-811fb50e1ca4.png)
是这样的，就是固定定位在底部的滚动条，如图的蓝框

**Comment by shinima** [comment]
已通过钉钉解决。

“可视窗口底部的滚动条” 表格已经默认提供了，不过生成这个滚动条有一定的前提条件：
* windows 系统（ mac 系统下默认没有滚动条，所以不可见）
* 表格上层元素没有设置额外的 overflow=auto/hidden （overflow 会导致 sticky position 失效）
