### ISSUE TITLE
表格不支持拖拽、编辑等功能

### ISSUE THREAD

**Issue by huangshiqiang** [alibaba/ali-react-table#141]
表格似乎不支持行拖拽排序和列拖拽排序功能、列宽调整等功能，请问要怎么扩展实现这些自定义功能呢？

**Comment by 52flutter** [comment]
try https://github.com/52flutter/react-base-table-extends

**Comment by shinima** [comment]
行拖拽排序、列拖拽排序  不会进行实现了（考虑虚拟滚动的情况下，实现起来太复杂了）
列宽调整 已在 v2.5 中进行实现
