### ISSUE TITLE
交叉表leftTree单元格自动合并功能 能否关闭

### ISSUE THREAD

**Issue by wyr1227** [alibaba/ali-react-table#142]
交叉表leftTree单元格自动合并功能 能否关闭

**Comment by kellywang1314** [comment]
我也想问，交叉表leftTree单元格是否合并，能不能支持自己配置

**Comment by shinima** [comment]
leftTree / topTree 传什么，交叉表就会渲染什么的。  可以通过处理 topTree / leftTree 来取消自动合并
