### ISSUE TITLE
交叉表能否增加序号功能

### ISSUE THREAD

**Issue by wyr1227** [alibaba/ali-react-table#143]
交叉表能否增加序号功能且不影响单元合并

**Comment by shinima** [comment]
添加这个可能会比较麻烦一些，我还没想到添加的好办法

**Comment by shinima** [comment]
`yarn add ali-react-table@2.4`
安装下 v2.4，然后可以参考下 [这个文档](https://ali-react-table.js.org/docs/pivot/cross-table#%E4%BA%A4%E5%8F%89%E8%A1%A8%E5%AE%9A%E5%88%B6) 和 [这个示例](https://ali-react-table.js.org/examples/others/cross-table-customization)
