### ISSUE TITLE
移动端竖屏模式下的问题

### ISSUE THREAD

**Issue by daguanjia** [alibaba/ali-react-table#146]
移动端竖屏模式 将div旋转90度 变成伪横屏  滚动会计算错误 。开启横屏是正常的 ，这个需要怎么做兼容？

**Comment by shinima** [comment]
伪横屏是通过 transform: rotate(90deg) 来实现的么？   目前的虚拟滚动没考虑 transform 的情况，一起使用的时候可能会出现计算错误，把虚拟滚动关掉试试看呢？

**Comment by daguanjia** [comment]
> 伪横屏是通过 transform: rotate(90deg) 来实现的么？ 目前的虚拟滚动没考虑 transform 的情况，一起使用的时候可能会出现计算错误，把虚拟滚动关掉试试看呢？

嗯通过 transform: rotate(90deg) 来实现的 但是会存在数据量大的表格 所以感觉关掉又不合适

**Comment by shinima** [comment]
试一下 v2.4 看看， 2.4 中对虚拟滚动做了重构
`yarn add ali-react-table@2.4`
