### ISSUE TITLE
不想用系统滚动条 想用自定义滚动条 有什么好的方式可以实现吗

### ISSUE THREAD

**Issue by han8435762** [alibaba/ali-react-table#149]
RT

**Comment by shinima** [comment]
参考这个例子就可以了

https://ali-react-table.js.org/docs/table/theming/#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%A0%B7%E5%BC%8F
