### ISSUE TITLE
请问下，关于总计和小计功能，如果小计只需要第一个维度的小计，不需要其他纬度的小计，是不是只能手动删除leftTreeRoot内部不要的小计的值。

### ISSUE THREAD

**Issue by kellywang1314** [alibaba/ali-react-table#153]

**Comment by shinima** [comment]
![image](https://user-images.githubusercontent.com/5550931/112133465-b3d97f00-8c06-11eb-9419-fc55fb030f3d.png)

根据需求在 `generateSubtotalNode` 中为相应的节点返回 null 就可以了。
