### ISSUE TITLE
请教下 在流水线中可以使用hooks API吗

### ISSUE THREAD

**Issue by 52flutter** [alibaba/ali-react-table#155]
比如我想data发现变化 然后做一些其他的处理 ，这样的场景是不是可以使用effect
我看官方的扩展功能中都没有使用hooks

**Comment by shinima** [comment]
可以的呀。     effect 和 pipeline 不冲突的，effect 该怎么用就怎么用。

pipeline 只是代替 Table props 的一种比较特别的写法而已（主要就是为了能够让表格能够按需引入功能拓展）。
