### ISSUE TITLE
滚动容器问题

### ISSUE THREAD

**Issue by BryanBao** [alibaba/ali-react-table#156]
当上层容器开启滚动，交叉表不做大小限制，可以在容器内发生虚拟滚动，但是表头固定可以自动完成，列锁定失效了，而在确定了交叉表的maxWidth之后，交叉表的自动列锁定可以生效，这块有什么解决办法吗？

**Comment by shinima** [comment]
想了下，这是个比较麻烦的情况。  表格的横向滚动目前总是发生在表格内部 （纵向滚动可以发生在表格组件内 或 组件外），而列锁定是基于横向的 sticky position 实现的，所以「当上层容器开启滚动」时 列锁定就会失效。

这个目前看起来没什么好办法，具体我再想想

**Comment by shinima** [comment]
这个目前没法解决，表格设计的时候 横向滚动就是在表格内部进行的。
