### ISSUE TITLE
表格是否支持类似于antd关闭边框的功能

### ISSUE THREAD

**Issue by aierweisi** [alibaba/ali-react-table#157]
![image](https://user-images.githubusercontent.com/33406910/112806433-58e1d500-90a9-11eb-9c31-917211914a44.png)
如图

**Comment by shinima** [comment]
设置一下 style 就可以了

```jsx
<BaseTable dataSource={dataSource} columns={columns} style={{
      '--cell-border-vertical': 'none',
      '--header-cell-border-vertical': 'none',
    }} />
```

![image](https://user-images.githubusercontent.com/5550931/112819358-18895380-90b7-11eb-8548-ceb18b58eddb.png)

**Comment by aierweisi** [comment]
好的，谢谢啦
