### ISSUE TITLE
Column 的Code 能不能 支持通过数组查询嵌套路径

### ISSUE THREAD

**Issue by Nokecy** [alibaba/ali-react-table#158]
[https://ant.design/components/table-cn/#Column](https://ant.design/components/table-cn/#Column)  像antd 的column dataIndex

**Comment by shinima** [comment]
这种情况下用 getValue 来代替 code 就可以了

或者先处理下 dataSource，把数据「打平」后用 code 来引用嵌套的数据~

也可以在 pipeline 上写一个拓展，等会儿我提供一下

**Comment by Nokecy** [comment]
~~大佬 来个示例~~ @shinima

**Comment by shinima** [comment]
```tsx
import _ from 'lodash';
import { makeRecursiveMapper, TablePipeline } from 'ali-react-table';
function codePath() {
  return (pipeline: TablePipeline) => {
    return pipeline.mapColumns(
      makeRecursiveMapper((col) => {
        if (Array.isArray(col.code)) {
          return {
            ...col,
            getValue(row) {
              return _.get(row, col.code);
            },
          };
        }
        return col;
      }),
    );
  };
}
```

使用 ↓
![image](https://user-images.githubusercontent.com/5550931/113243513-bd897380-92e5-11eb-8a6f-0f654bb203c3.png)


效果 ↓
![image](https://user-images.githubusercontent.com/5550931/113243524-c5491800-92e5-11eb-9355-8d19b3e88f38.png)
