### ISSUE TITLE
如何取消表格的顶部滚动条

### ISSUE THREAD

**Issue by aierweisi** [alibaba/ali-react-table#160]
如下图，有时候在window环境会出现表格的顶部滚动条，这个有办法去掉吗
![image](https://user-images.githubusercontent.com/33406910/113114673-29b09c80-923e-11eb-8de5-2e5f0ba7fbfb.png)

**Comment by shinima** [comment]
这个应该是隐藏滚动条的样式代码失效了，检查下是不是有什么地方把样式给覆盖了

正常情况 ↓

![image](https://user-images.githubusercontent.com/5550931/113150819-0ea65280-9267-11eb-9341-f8e9ff0ec18f.png)
