### ISSUE TITLE
支持手动订制分组吗？

### ISSUE THREAD

**Issue by melin** [alibaba/ali-react-table#162]
支持手动订制分组吗？类似下图效果，也是一个很常见的需求，多个统计指标，再按照某种类型分组。
![image](https://user-images.githubusercontent.com/1145830/114306132-741efc80-9b0d-11eb-887d-7114023d896f.png)

**Comment by shinima** [comment]
你给的图片中的样子是支持的呀。 可以使用 column.children 来设置列的分组关系：

```js
const group1 = [ { name: '访客数' }, { name: '支付金额' }, ... ]
columns = [ { name: '分组1', children: group1 }, { name: 'foo', code: 'foo' } ]
```
