### ISSUE TITLE
拖拽调整列宽功能

### ISSUE THREAD

**Issue by miracleDD** [alibaba/ali-react-table#165]
1.x版本的调整列宽功能还能在最新版本用吗？ 
支持antd那种利用react-resizable 调整表头宽度吗？

**Comment by shinima** [comment]
拖拽调整列宽功能已经在开发了，预计本周末（4.18）会发布

**Comment by miracleDD** [comment]
@shinima 真棒！期待~

**Comment by shinima** [comment]
@miracleDD   v2.5 中已支持
详见   https://ali-react-table.js.org/docs/pipeline/features/column-resize
