### ISSUE TITLE
单元格合并问题

### ISSUE THREAD

**Issue by miracleDD** [alibaba/ali-react-table#174]
当启用了autoRowSpan后，列的单元格合并是生效的。但是想把已经合并的这列某个单元格再和下一列的单元格合并，就不生效了。
组件里有没有提供什么方法能做到下图这种合并？
![image](https://user-images.githubusercontent.com/9331702/116512279-5bc72400-a8fa-11eb-9491-72728d42bba4.png)

**Comment by shinima** [comment]
这种暂时没有哈，需要在上层自行实现 column.getCellProps 或者 column.getSpanRect

**Comment by miracleDD** [comment]
我用column.getSpanRect也尝试过，设置了行合并后生效，再设置第一行的第一个单元格列合并就不生效了。
两次设置都在同一column下设置，要怎么写才能实现上图合并呢？我看Antd里是可以在column的render里单独给单元格设置合并的，这个组件里没找到~

**Comment by shinima** [comment]
“性别”列 ： 
- 在 rowIndex=0 时， getCellProps 需要返回 `{ rowSpan: 1, colSpan: 2 }`；
- 在 rowIndex=1 时， getCellProps 需要返回 `{ rowSpan: 5, colSpan: 1 }`；
- 在 rowIndex=6 时， getCellProps 需要返回 `{ rowSpan: n, colSpan: 1 }`；

根据你的需求，在 getCellProps 返回相应的 rowSpan/colSpan 哈

**Comment by miracleDD** [comment]
@shinima 我之前是用rowIndex判断，放在两个方法分别在columns中的getSpanRect写的，判断有点儿问题导致没生效。谢谢啦~我把问题关了哈。
