### ISSUE TITLE
addition the ellipsis attribute of the table column and use the tooltip to display all the content

### ISSUE THREAD

**Issue by lucaslz2020** [alibaba/ali-react-table#175]
such as antd table column attribute ellipsis

**Comment by lucaslz2020** [comment]
#95 Can you add custom events to the tag td of art-table-cell?

**Comment by shinima** [comment]
This could be implemented in user-land code. Just set `column.render` to a function which return a div that has overflow=hidden and has a Tooltip inside.

**Comment by lucaslz2020** [comment]
Thanks, but this way is very cumbersome to write, every time you have to import Tooltip, it is not simple enough

**Comment by shinima** [comment]
ali-react-table is not designed to be a table component with all features that works out-of-box. As the name `BaseTable` indicates, we encourage you to encapsulation the common table features according to your business needs. The table component focuses on performance and extensibility, so `addition the ellipsis attribute` is assumed to be implemented in user-land code.
