### ISSUE TITLE
树状列表的展开图标可以自定义吗?

### ISSUE THREAD

**Issue by SH748** [alibaba/ali-react-table#178]
类似于antd的配置项，可以自定义图标或者隐藏展开图标。
另：是否可以在css上区分一下数据的层级，方便不同主题时给不同层级数据加颜色

**Comment by shinima** [comment]
可以是可以，就是选项越加越多，太烦了…

建议直接基于默认的 treeMode 实现，改造一个自己的 treeMode 好了

源码在这儿：  https://github.com/alibaba/ali-react-table/blob/master/packages/ali-react-table/src/pipeline/features/treeMode.tsx

**Comment by shinima** [comment]
这个需求不太常见，建议直接基于源码进行改造吧，根据需求裁剪一下 treeMode 的实现，应该也不麻烦。     我平时工作太忙了，维护不动那么多的选项……  ╮(╯-╰)╭
