### ISSUE TITLE
firefox 在表头和表格体下方同时出现横向滚动条

### ISSUE THREAD

**Issue by guonanci** [alibaba/ali-react-table#180]
Mac 上的表现：
<img width="660" alt="firefox-art-twoScrollBars-on-header-and-body" src="https://user-images.githubusercontent.com/12762626/117535808-05f52900-b02a-11eb-9a79-f02c58235461.png">
Windows 上的表现：
![firefox-art-twoScrollBars-on-header-and-body-Windows](https://user-images.githubusercontent.com/12762626/117535835-376df480-b02a-11eb-8acb-bbed44249754.png)

官方 example 就可以复现：
https://ali-react-table.js.org/docs/table/basic-usage

**Comment by guonanci** [comment]
chrome 上只有下面的滚动条

**Comment by shinima** [comment]
这个应该是样式被覆盖的问题，表头部分应该是有一个隐藏滚动条的 CSS 样式的， 我看下为什么没生效。

**Comment by guonanci** [comment]
@shinima  应该是这里没做火狐的隐藏滚动条样式兼容？
![no-scrollbar](https://user-images.githubusercontent.com/12762626/117600865-68ac0900-b17f-11eb-931f-02985a94b142.png)

**Comment by lucaslz2020** [comment]
window 也有~

**Comment by shinima** [comment]
v2.6.1 版本已更新，一定程度上解决了 firefox 上的滚动条问题。

但 firefox 和 chrome 两个浏览器的滚动行为差别很大，chrome 中的流畅滚动放到 firefox 中很可能出现卡顿，试了好多次，暂时没有什么好的解法，firefox 目前只能说…勉强可用…
