### ISSUE TITLE
getRowProps与rowSelection有冲突

### ISSUE THREAD

**Issue by lucaslz2020** [alibaba/ali-react-table#182]
使用`getRowProps`自定义一些`className`会导致`singleSelect`、`multiSelect`扩展
中的`onChange`事件不回调
#169

**Comment by shinima** [comment]
能给个具体一些的例子么？  方便我复现一下

**Comment by lucaslz2020** [comment]
@shinima https://codesandbox.io/s/sleepy-perlman-h1v9g?file=/src/App.js

**Comment by lucaslz2020** [comment]
@shinima 发现使用`lock`也会与`singleSelect`和`multiSelect `冲突，导致`lock`左边不能锁列

**Comment by shinima** [comment]
> 发现使用lock也会与singleSelect和multiSelect 冲突，导致lock左边不能锁列

@lucaslz2020 使用 singleSelect/multiSelect 的时候在 options 中设置 `radioColumn.lock = true` 或 `checkboxColumn.lock = true` 就可以正常 lock 了

**Comment by shinima** [comment]
https://ali-react-table.js.org/docs/pipeline/#hooks-%E7%94%A8%E6%B3%95

![image](https://user-images.githubusercontent.com/5550931/118076259-4a931280-b3e4-11eb-8970-ca8ab5e3a470.png)

**Comment by lucaslz2020** [comment]
@shinima thanks
