### ISSUE TITLE
在singleSelect/multiSelect中支持合并多行吗？

### ISSUE THREAD

**Issue by lucaslz2020** [alibaba/ali-react-table#183]
就像在`column`中使用getCellProps的`rowSpan`进行合并

**Comment by shinima** [comment]
可以具体试下，我也不知道可不可以，没考虑过这种情况

**Comment by lucaslz2020** [comment]
@shinima 就是没试出来~

**Comment by lucaslz2020** [comment]
@shinima 在`singleSelect/multiSelect`中不支持重写`getCellProps`方法，所以不支持，是否可以考虑支持一下？比如在``singleSelect/multiSelect`中添加`rowSpan`属性放入`getCellProps`中

**Comment by shinima** [comment]
这些定制已经超出普通表格的范围了，直接在用户代码中 [fork 一个 singleSelect](https://github.com/alibaba/ali-react-table/blob/master/packages/ali-react-table/src/pipeline/features/singleSelect.tsx) 然后定制吧
