### ISSUE TITLE
主题切换示例看不懂，是否可以提供可运行的样例？

### ISSUE THREAD

**Issue by RedScarf007** [alibaba/ali-react-table#186]
[主题样例代码](https://ali-react-table.js.org/docs/table/theming#主题切换示例)

文章中`assets.biz`指的是什么？

**Comment by lucaslz2020** [comment]
直接看仓库源码吧，里面有

**Comment by shinima** [comment]
assets.biz  里边放了一些表格测试数据，大部分时候不关心这个哈

**Comment by shinima** [comment]
主题切换示例的主要意思是……  先配置好若干套主题（每套主题对应一个的 Table 组件），切换主题的时候，就切换为相应的 Table 组件。

例如这里就有一个 [ant design 风格的表格](https://github.com/alibaba/ali-react-table/blob/df14d40a0c7708ba8e31259e00dfb9c7d21e3f84/packages/website/src/assets/AntdBaseTable.tsx)
