### ISSUE TITLE
列拖动时，会触发列排序

### ISSUE THREAD

**Issue by Nokecy** [alibaba/ali-react-table#188]

**Comment by shinima** [comment]
不是很明白你的意思。  能详细说下不

**Comment by Nokecy** [comment]
列拖动和列排序同时存在时，拖动列结束后，会触发排序动作

**Comment by shinima** [comment]
这描述的太模糊了，能给个复现 demo 么？

可以基于这个模板 https://codesandbox.io/s/ali-react-table-online-demo-w2wte

**Comment by Nokecy** [comment]
https://codesandbox.io/s/ali-react-table-online-demo-forked-2m21s?file=/index.js

复现操作
1、向左缩小第一列宽度，鼠标停留在第一列列头，这时鼠标变为手型
2、放开鼠标，这时会触发排序动作
@shinima

**Comment by shinima** [comment]
ok   明白了。   这是事件冒泡的缘故，我加个选项来允许上层来阻止事件冒泡吧。

**Comment by Nokecy** [comment]
@shinima  大佬 这个有空添加一下吧~~~

**Comment by lucaslz2020** [comment]
@shinima 这个阻止事件冒泡还不能彻底解决，拖动列的时候，鼠标可能移动到了`排序上面`，误触排序`onClick`

**Comment by PiccoloYu** [comment]
@shinima 同求解决方案 或者 大佬更新一下 暴露配载

**Comment by shinima** [comment]
下面两个方式，二选一，可以解决这个问题：

1. 先调用 `features.sort(...)`，再调用 `features.columnResize(...)`，一定程度上可以解决该问题；如果这个不行，可以换成下面的方式
2. 升级到 2.6.1，在使用 sort 时设置 `options.clickArea = 'icon'`

**Comment by lucaslz2020** [comment]
@shinima
我是加了一个onClick事件. 稍微好了那么一点点

```
 <ResizeHandle
                className="resize-handle"
                var-handleBackground={opts.handleBackground}
                var-handleHoverBackground={opts.handleHoverBackground}
                onClick={(e) => e.stopPropagation()}
                onMouseDown={(e: React.MouseEvent<HTMLSpanElement>) => {
                  startResize(startIndex, endIndex, e)
                }}
              />
```
