### ISSUE TITLE
可以重写表格cell吗？和antd的component似的

### ISSUE THREAD

**Issue by zhangzhi93** [alibaba/ali-react-table#19]
可以重写表格cell吗？和antd的component似的

**Comment by shinima** [comment]
设置一下 column.render 就可以了

**Comment by zhangzhi93** [comment]
> 设置一下 column.render 就可以了
如果要对某行的tr重写class，有什么方法吗？或者如果需要拖拽排序，可以加吗？

**Comment by shinima** [comment]
@zhangzhi93  自定义每一行 tr 的 props 用  `getRowProps(...)` 就可以了

拖拽排序比较复杂，我还不确定能不能做…  回头我试试用 react-dnd 写个示例

**Comment by tonyabracadabra** [comment]
请问行和列的拖拽排序有例子了么？谢谢！

**Comment by shinima** [comment]
@tonyabracadabra   这个做起来很麻烦  😂   使用频率也不高，就没做
