### ISSUE TITLE
渲染顺序和数据顺序不同，导致排序不生效

### ISSUE THREAD

**Issue by kellywang1314** [alibaba/ali-react-table#195]
你好，请问下，buildDrillTree这个函数是会自动排序吗，为什么我的元数据的顺序和函数处理之后的顺序不同
![image](https://user-images.githubusercontent.com/26647100/120418177-9fe29400-c392-11eb-81c9-599d2887b1ef.png)

![image](https://user-images.githubusercontent.com/26647100/120418245-bc7ecc00-c392-11eb-91a0-fc368790d06a.png)

**Comment by kellywang1314** [comment]
是由于groups使用的对象，会对key为数组的重新排序，导致排序失效，是否可以把对象改成map结构，或者可选？

**Comment by shinima** [comment]
已在 2.5.2 中修复
