### ISSUE TITLE
在列少的情况下 ，column的宽度与预期不符。

### ISSUE THREAD

**Issue by PiccoloYu** [alibaba/ali-react-table#207]
在列少的情况下 ，column的宽度与预期不符。
https://codesandbox.io/s/ali-react-table-column-width-824t2?file=/src/App.js
我序号只想要60px 但是实际长度不止。
在 Elements 调试。只有两种方法。
取消 table 的 100% 属性。   （不合理）
以及取消 table colgroup col 最后一列或者其中一列的 宽度 ，也就是有一列自适应宽度。
https://codesandbox.io/s/ali-react-table-column-width-824t2?file=/src/styles.css

**Comment by shinima** [comment]
这其实是 html table 元素（table-layout: fixed）的默认行为，当所有列的宽度和小于 table 的宽度时，列宽会自动变大 使得所有列充满表格宽度。   表格组件对这个并没有做特殊处理，所以目前的行为其实就是预期的行为。

**Comment by lucaslz2020** [comment]
@shinima 这个有解决方案没有啊~

**Comment by shinima** [comment]
我想的是可以用 ResizeObserver 监听表格宽度变化，然后在上层手动计算出每一列的宽度。
但这个实现起来需要花不少时间，目前工作比较忙，所以……  暂时没有解决方案

**Comment by lucaslz2020** [comment]
@shinima 如果是这样的话跟我的想法差不多， 我的想法是，根据已经设置过的宽，计算出未设置的宽数量，总宽度减去已设置的宽总宽度。平均出未设置的宽度

**Comment by lucaslz2020** [comment]
本来我想通过ref 使用BaseTable state 中的`maxRenderWidth`
