### ISSUE TITLE
sort自定义颜色

### ISSUE THREAD

**Issue by LitterPig** [alibaba/ali-react-table#21]
排序的svg在排序的时候可以自定义颜色吗？我目前不想用默认的#23A3FF和#bfbfbf

**Comment by shinima** [comment]
这个没问题，我在 sort 的 options 中透出两个新的字段吧，允许上层配置激活和未激活的颜色

**Comment by LitterPig** [comment]
![image](https://user-images.githubusercontent.com/19744021/79521841-bf363900-808c-11ea-9400-dc5879909a12.png)
没有看到呀？还是其他地方？

**Comment by LitterPig** [comment]
commonTransforms.sort(options: SortOptions)：表格排序
该 transform 会同时对 dataSource 和 columns 进行更新
该 transform 会根据 options.sorts 来排序 dataSource
options.mode=multiple （默认值）时支持多字段排序（先按字段 1 排序，然后按字段 2 排序，依次类推）
options.mode=single 时表现为单字段排序
无论是多字段还是单字段排序，options.sorts 始终为一个数组
该 transform 支持树状结构数据的排序，即同一个节点下的子节点才会进行相互比较
注意排序字段对应的列必须有 column.features.sortable = true 的配置，否则将会忽略该字段的排序
features.sortable = true 时默认为自然序（对于数字）或字典序（对于字符串）
我们可以通过给 features.sortable 传递一个函数来自定义比较规则，该函数将被作为 Array#sort 的参数
options.orders 可以用来指定排序切换顺序
默认值为 ['desc', 'asc', 'none']，即连续点击某一列的表头时，先按降序排序，然后按升序排序，最后取消排序
如果要传入自定义的 orders，需要满足以下规则：
none 不能作为 orders 的第一个元素
none 必须在 orders 中
SortOptions 类型见下方
type SortOptions = {
  sorts: Array<{ code: string; order: 'asc' | 'desc' }>
  onChangeSorts(nextSorts: Array<{ code: string; order: 'asc' | 'desc' }>): void
  orders?: Array<'asc' | 'desc' | 'none'>
  mode?: 'single' | 'multiple'
}

**Comment by shinima** [comment]
@LitterPig  抱歉，我的说法有点问题。   目前还不支持，我的意思是等下一个小版本我会加上

**Comment by LitterPig** [comment]
希望可以尽快实现呀~那我可以自定义sort的图标吗？因为现在是svg的吗，我想自己传i标签进去，这个目前支持吗

**Comment by shinima** [comment]
> 那我可以自定义sort的图标吗？因为现在是svg的吗，我想自己传i标签进去，这个目前支持吗

@LitterPig 现在还不支持。

我想了想大概有两个方案…

1. 第一个是我给 sort 开放一些选项或者回调，让上层来控制 sort 表头的一部分渲染
2. 第二个是我开放一下 sort 内部用到的数据处理方法，上层根据这些方法就能实现完全自定义的排序功能了

当然这两个方案也不冲突，我先添加一些选项或者回调吧

**Comment by LitterPig** [comment]
嗯啊，可以方便加个聊系方式吗~

**Comment by shinima** [comment]
@LitterPig  功能已经实现了，过会儿我去发个版本
