### ISSUE TITLE
虚拟滚动 Table 是否支持 WindowScroller？

### ISSUE THREAD

**Issue by jeasonstudio** [alibaba/ali-react-table#211]
参考：https://bvaughn.github.io/react-virtualized/#/components/WindowScroller

**Comment by shinima** [comment]
https://ali-react-table.js.org/examples/big-data?example=%E6%BB%9A%E5%8A%A8%E5%AE%B9%E5%99%A8%E4%B8%BAwindow

@jeasonstudio  看下这个是否符合你的预期？
