### ISSUE TITLE
树形选择时，treeMode的isLeafNode没有在treeSelect中体现。

### ISSUE THREAD

**Issue by Cool-Star** [alibaba/ali-react-table#214]
treeSelect的checkedStrategy：‘child’方式下，判断叶子节点依然是根据最下层的对象，而没有使用已经设置的isLeafNode方法。

**Comment by Cool-Star** [comment]
然而，在treeSelect中设置了isLeafNode方法后成功，但此处在文档中并未体现，隐藏的api吗？

**Comment by shinima** [comment]
目前应该是这样的：  treeMode 有 options.isLeafNode； treeSelect 没有 options.isLeafNode

「在treeSelect中设置了isLeafNode方法后成功」 这个能给个具体一些的例子么？

**Comment by Cool-Star** [comment]
> 目前应该是这样的： treeMode 有 options.isLeafNode； treeSelect 没有 options.isLeafNode
> 
> 「在treeSelect中设置了isLeafNode方法后成功」 这个能给个具体一些的例子么？

实际上在我在treeMode中设定了特殊的子节点的判定方式，然后再treeMode中设置了checkedStrategy只选中子节点。。但是treeMode的选择中并没有参照treeMode所设定的判断逻辑。
