### ISSUE TITLE
生产环境 styled 样式问题

### ISSUE THREAD

**Issue by ppxu** [alibaba/ali-react-table#215]
官方demo [table](https://ali-react-table.js.org/examples/table) 中，查看元素，表格有个 .kksiKu 的样式文件，

![image](https://user-images.githubusercontent.com/1119778/124564655-dcaf1880-de73-11eb-8691-e2547b652055.png)

点击右侧的 style 标签，会跳到一个空的标签

![image](https://user-images.githubusercontent.com/1119778/124564751-f51f3300-de73-11eb-8a46-7be00a3cc8a0.png)

而且如果把这个空的 style 标签删掉，表格样式就没了，想知道这块是什么原因，表格的css内容到底在哪里

**Comment by shinima** [comment]
这是 styled-components 利用 CSSOM 接口生成的样式表， 具体的 CSS 规则在浏览器 inspector 中不可见。

如果需要查看 CSS 内容，可以选中 style tag 后执行以下代码：

`Array.from($0.sheet.rules).map(r => r.cssText).join('\n\n')`

![image](https://user-images.githubusercontent.com/5550931/124567914-fc940b80-de76-11eb-915b-091abf37ae6b.png)

**Comment by ppxu** [comment]
> 这是 styled-components 利用 CSSOM 接口生成的样式表， 具体的 CSS 规则在浏览器 inspector 中不可见。
> 
> 如果需要查看 CSS 内容，可以选中 style tag 后执行以下代码：
> 
> `Array.from($0.sheet.rules).map(r => r.cssText).join('\n\n')`
> 
> ![image](https://user-images.githubusercontent.com/5550931/124567914-fc940b80-de76-11eb-915b-091abf37ae6b.png)

这个配置可以手动调整吗，这边现在碰到了一些比较特殊的样式丢失问题

**Comment by ppxu** [comment]
解决了，styled-components 有个配置 disableCSSOMInjection，用 StyleSheetManager 包一下就可以了
