### ISSUE TITLE
排序 clickArea 不生效

### ISSUE THREAD

**Issue by FinE54** [alibaba/ali-react-table#220]
使用了，拖拽调整列宽与 Sort 两个 pipeline
拖拽调整列宽会触发 Sort 排序，嗯………………然后我去设置 sort 的 clickArea，并不生效。
看打包的 ali-react-table.js ，sort 相关 opt 的也没看到 clickArea 这个参数。。😂

**Comment by shinima** [comment]
我本地验证下…   😂

**Comment by FinE54** [comment]
通过 SortHeaderCell 自定义表头，把点击事件挂在 Icon 上解决了🤣

**Comment by shinima** [comment]
我试了下 clickArea 是生效的呀，注意要装最新版本的 ali-react-table，这是最近才加的功能。

在线 demo：  https://codesandbox.io/s/ali-react-table-online-demo-forked-csxt7?file=/index.js

**Comment by drizzlesconsin** [comment]
@shinima  如下配置，点击行时好像无法响应选中操作
```tsx
clickArea: 'row',

getRowProps={(row) => {
  return {
    className: 'xxx',
  };
}}
```
