### ISSUE TITLE
crosstable怎么设置列不进行锁定？

### ISSUE THREAD

**Issue by jennyrenjiale** [alibaba/ali-react-table#233]
目前左侧的聚合项太多了，因为列默认锁定，会有遮住右侧指标值的问题。
怎样才能取消锁定啊？

**Comment by shinima** [comment]
![image](https://user-images.githubusercontent.com/5550931/132862638-1ef2f673-a8a5-4f64-bd3c-cb56209a5794.png)

可以通过 leftMetaColumns 来设置左侧锁列的配置
