### ISSUE TITLE
怎么指定是在table的body里面滚动而不是在外部容器滚动

### ISSUE THREAD

**Issue by Linginnn** [alibaba/ali-react-table#237]
就像这样<img width="1325" alt="WeChat55cbbcead233431f1fed952648d57413" src="https://user-images.githubusercontent.com/16818104/131775919-9074a23a-4752-45e5-9ead-e84cb9f0af04.png">

**Comment by shinima** [comment]
`<BaseTable style={{ maxHeight: 200, overflow: 'auto' }} />`
