### ISSUE TITLE
编译错误问题

### ISSUE THREAD

**Issue by nuonuo534** [alibaba/ali-react-table#24]
Failed to compile.

./node_modules/ali-react-table/dist/chunks/ali-react-table-table-d315bfb5.esm.js
Module parse failed: Unexpected token (355:31)
You may need an appropriate loader to handle this file type.
|             if (column.width == null) {
|                 if (defaultColumnWidth != null) {
|                     column = { ...column, width: defaultColumnWidth };
|                 }
|                 else if (process.env.NODE_ENV !== 'production' && isLeafNode(column) && column.lock) {

运行时出现不能编译...解构语句错误，但是node_modules包应该是已经balbel或者ts-loader处理过的文件，不应该出现...语法问题

**Comment by shinima** [comment]
因为表格只支持较新版本的浏览器，而这些浏览器都已经支持了 `...` 语法，所以编译的时候我没有转义这个语法。 

不过项目中的一些编译工具可能仍然无法识别这个语法，我在下一个小版本把 `...` 处理一下吧

**Comment by shinima** [comment]
已经在 #26 中修复
