### ISSUE TITLE
表头设置气泡，报错hooks

### ISSUE THREAD

**Issue by goSeeFuture** [alibaba/ali-react-table#255]
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (react-dom.development.js:14724)
    at useState (react.development.js:1497)
    at useTablePipeline (ali-react-table-pipeline-72600030.esm.js:2318)

**Comment by shinima** [comment]
tips 里面没有用到 hooks。  这个问题应该来自于业务代码。
