### ISSUE TITLE
交叉表中如何设置leftTree宽度

### ISSUE THREAD

**Issue by The-End-Hero** [alibaba/ali-react-table#256]
![image](https://user-images.githubusercontent.com/19590233/136652218-9e7bbc46-f99e-49e4-a60a-7503c0900d5d.png)
如图，交叉表中如何设置leftTree这部分的宽度呢？

**Comment by shinima** [comment]
设置一下 `props.leftMetaColumns={[ { width: 150 }, { width: 200} ]}`
