### ISSUE TITLE
表头第一列与第二列合并无效

### ISSUE THREAD

**Issue by kevinqqqq** [alibaba/ali-react-table#260]
你好，在使用普通表格模拟 透视图的时候，表头遇到一个问题，不知如何处理 这是我做出来的效果
![image](https://user-images.githubusercontent.com/3383489/141481449-b851ad2f-1cac-4ba3-8b2b-2feb02c2dcbf.png)

实际我要显示的效果
![image](https://user-images.githubusercontent.com/3383489/141481517-03ca4a64-fdce-4a92-baf3-442a00212e90.png)

在columns的children中，不知道如何设置属性可以让最后一列跳过第二列绘制th

尝试的columns中所有的api 都没有达到想要的效果，求助大佬

**Comment by shinima** [comment]
这个目前不支持。这个限制来自是组件本身，在[这里](https://github.com/alibaba/ali-react-table/blob/53c6b3220ae46ffd364868ba4783161235269aa4/packages/ali-react-table/src/base-table/header.tsx?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L209)可以看到只有叶子节点的column 才会有 rowSpan...      这个建议先忍一下吧，一般来说也不会太影响使用体验。

**Comment by kevinqqqq** [comment]
感谢你的回复
今天在写demo的时候遇到了第二个问题
参考官方示例  列合并
原本要达到的效果 
![image](https://user-images.githubusercontent.com/3383489/141615030-917e0ec8-1516-47e1-bb5b-7420c02c9332.png)

使用 autospan前的效果
![image](https://user-images.githubusercontent.com/3383489/141615099-473849fc-0275-4faa-ab25-d84f2cfee6f1.png)

使用 autospan后的效果
![image](https://user-images.githubusercontent.com/3383489/141615070-55a0b8fa-8036-4199-8083-978a55e2e605.png)

**Comment by kevinqqqq** [comment]
解决了 感谢  用 columnsgetCellProps
