### ISSUE TITLE
请问交叉表模式，leftTree顶部的空白单元格可以配置内容吗？

### ISSUE THREAD

**Issue by iqshen** [alibaba/ali-react-table#275]
如图，期望在这里配置一些内容。请问支持吗?
![image](https://user-images.githubusercontent.com/24309546/149263006-8d2d79cd-833a-4a72-adf6-d1bfd616dc5e.png)

**Comment by iqshen** [comment]
目前在文档和ts描述里，没有发现可以配置的地方。

**Comment by shinima** [comment]
按下面的方式进行配置即可

leftMetaColumns={
  { name: 'foo' },
  { name: 'bar' },
}

**Comment by iqshen** [comment]
> 按下面的方式进行配置即可
> 
> leftMetaColumns={ { name: 'foo' }, { name: 'bar' }, }

thanks
