### ISSUE TITLE
树状的table展开和收缩的时候，能不能自己自定义一个颜色，或者和之前排序一样，将SortHeaderCell暴露出来，自定义

### ISSUE THREAD

**Issue by LitterPig** [alibaba/ali-react-table#30]
![image](https://user-images.githubusercontent.com/19744021/79965015-16d60980-84be-11ea-9690-d9671d69f4fd.png)
因为我们使用表格的时候，一般数据都比较多，有时候点点就不知道我上次点开的是哪一个了，所以我想传进去一个自定义颜色，让我知道点开的是哪一个。收拢后颜色恢复

**Comment by shinima** [comment]
@LitterPig 你看下是否可以通过 `BaseTableProps#getRowProps` 来达成实现一样的效果？ 就是根据最近一次 treeOptions.onChangeOpenKeys 回调中的 action & key，设置一下最近展开的行的背景色就好了。


```javascript
function Component() {
  const [openKeys, onChangeOpenKeys] = useState([]);
  const [lastOpenKey, setLastOpenKey] = useState("");

  const renderData = applyTransforms(
    inputDataSourceAndColumns,
    commonTransforms.treeMode({
      primaryKey: "id",
      openKeys,
      onChangeOpenKeys(nextKeys, key, action) {
        // 记录最近一次被展开的 key
        if (action === "expand") {
          setLastOpenKey(key);
        } else {
          setLastOpenKey("");
        }
        onChangeOpenKeys(nextKeys);
      },
    })
  );

  return (
    <div>
      <BaseTable
        dataSource={renderData.dataSource}
        columns={renderData.columns}
        getRowProps={(row, rowIndex) => {
          // 根据最近一次被展开的 key 来设置行的背景色
          if (row.key === lastOpenKey) {
            return { style: { background: "#ccc" } };
          }
        }}
      />
    </div>
  );
}
```

如果还是想自定义箭头的颜色的话，我这边可以将相关的配置项开出来。

**Comment by LitterPig** [comment]
你这个只能设置单元格的颜色吧，我其实想设置收拢和展示箭头的颜色

**Comment by shinima** [comment]
@LitterPig  好的   这个等我周六加一下吧

**Comment by shinima** [comment]
@LitterPig 已经实现好了
因为这个功能并非常见功能，需要在通过 CSS 类名来控制样式，可以参考[这个示例](https://ali-react-table.js.org/?path=/story/%E7%A4%BA%E4%BE%8B-%E6%A0%91%E7%8A%B6%E8%A1%A8%E6%A0%BC%E4%B8%AD%E7%9A%84%E6%9C%80%E8%BF%91%E5%B1%95%E5%BC%80%E6%A0%87%E8%AE%B0--tree-table-with-last-open-mark)
