### ISSUE TITLE
columns第一位如果使用children  导致dataSource不会识别树形数据

### ISSUE THREAD

**Issue by lz-59** [alibaba/ali-react-table#300]
![image](https://user-images.githubusercontent.com/57341195/163556369-1728e5b0-4598-4bd4-83c8-8333d8c2e171.png)

**Comment by shinima** [comment]
嗯，现在就是这么设计的。     treeMode 只支持 「columns[0] 没有 children」的情况。

**Comment by cnwhy** [comment]
@shinima 有什么特殊顾虑么，我也碰到了这个情况，树表格或者带详情的表格都会有这个问题；  
本来想 PR 过来，不过翻到这个 issues 我犹豫了, 加了一个更新第一个页子节点的工具方法

```ts
import { ArtColumn } from '../interfaces'
/**
 * 更新第一个叶子节点列配置
 */
export default function upDataFirstCol(columns: ArtColumn[], upFn:(firstCol:ArtColumn)=>ArtColumn):ArtColumn[]{
  const [firstCol, ...others] = columns;
  if(firstCol.children && firstCol.children.length){
    firstCol.children = upDataFirstCol(firstCol.children, upFn)
    return [...columns];
  }else{
    return [
      upFn(firstCol),
      ...others
    ]
  }
}
```
[fix: 当表头分组第一列就在组内时，树表格和带详情的功能失效](https://github.com/cnwhy/ali-react-table/commit/65b2680b70fb7aaae0c087ff2cec925756862065)
@lz-59

**Comment by shinima** [comment]
@cnwhy 没什么特殊考虑。     在阿里工作一直很忙，加太多功能没精力维护了（其实现在已经没什么精力了，请大家见谅）

**Comment by cnwhy** [comment]
@shinima 理解，有时间 code review 一下，我提两个PR
