### ISSUE TITLE
透视表点击排序 左树 数据展示错误

### ISSUE THREAD

**Issue by feEden** [alibaba/ali-react-table#307]
![image](https://user-images.githubusercontent.com/46083022/169239659-72c3cace-a3dd-4041-862d-100fd4b5185d.png)
![image](https://user-images.githubusercontent.com/46083022/169239686-ccb49151-8442-45a3-8cfd-8ee5a3834fe8.png)

ali-react-table": "^2.6.1",

如上图所示，点击第一周排序，左树 数据展示错误
https://codesandbox.io/s/nervous-jones-e0o15n?file=/src/App.tsx

**Comment by shinima** [comment]
透视表的排序很复杂， 不能与 ali-react-table 内置的 sort 搭配使用。

**Comment by feEden** [comment]
> 

那有其他法子么

**Comment by feEden** [comment]
> 

那有其他法子么 @shinima
