### ISSUE TITLE
移动端表格上滑动和下滑动，会卡住

### ISSUE THREAD

**Issue by LitterPig** [alibaba/ali-react-table#32]
- [ ] 

- [ ]

**Comment by LitterPig** [comment]
而且我发现，如果去掉lock:true,这个问题就不会出现

**Comment by shinima** [comment]
目前表格还还不支持移动端，在移动端上表现有问题是正常的。

有空我会把一些在移动端上显而易见的问题修复，但是不推荐在移动端上使用这个表格。

**Comment by LitterPig** [comment]
恩啊，期待~

**Comment by shinima** [comment]
试一下 1.0 版本的呢。  1.0 对 DOM 结构进行了简化，调整比较大，在我手机上已经可以正常的上下滑动了
