### ISSUE TITLE
React 18 下滚动会出现很明显的白屏

### ISSUE THREAD

**Issue by Cool-Star** [alibaba/ali-react-table#325]
在升级到react18以后，开启虚拟滚动后，滚动会先白屏再正常。
推测可能是先显示了滚动位置的样式再渲染导致

**Comment by Cool-Star** [comment]
fork后使用react18下的强制渲染更新解决。

**Comment by lovewaner** [comment]
您好，能具体说下解决方案吗？我现在也遇到了这个问题
