### ISSUE TITLE
是否可以支持下resize column

### ISSUE THREAD

**Issue by wzz5304** [alibaba/ali-react-table#33]
缺少自定义拖动列宽，是否可以考虑支持下，这个场景用到的还是比较普遍的。谢谢！

**Comment by shinima** [comment]
嗯，这个功能已经在加了

**Comment by wzz5304** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"肥超"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月9日(星期六) 下午5:13
收件人:&nbsp;"alibaba/ali-react-table"<ali-react-table@noreply.github.com&gt;;
抄送:&nbsp;"Goldlion"<530491092@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/ali-react-table] 是否可以支持下resize column (#33)





 
嗯，这个功能已经在加了

**Comment by shinima** [comment]
@wzz5304  已经在 0.13.2 中添加，详见  https://ali-react-table.js.org/?path=/story/表格功能拓展-常用功能-拖拽调整列宽--page
