### ISSUE TITLE
问下，怎么固定第一行数据？

### ISSUE THREAD

**Issue by yuhaoz** [alibaba/ali-react-table#340]
问下，怎么固定第一行数据？

**Comment by HuColin** [comment]
在不开启虚拟滚动的情况下，可以通过 css 样式覆盖的方式设置 表格的容器高度为 100%，然后设置第一行的 postion 为 sticky
效果如下：
![image](https://github.com/alibaba/ali-react-table/assets/16102181/faaaeef8-54cb-4804-a949-c8e9243bab9f)
![image](https://github.com/alibaba/ali-react-table/assets/16102181/3443d883-1d1d-42eb-8fe6-d12b247b7108)
甚至可以通过 `getRowProps` 指定特定行数具有吸顶的效果

**Comment by yuhaoz** [comment]
谢谢
