### ISSUE TITLE
会出现thead和tbody有空隙的情况。

### ISSUE THREAD

**Issue by 273403986** [alibaba/ali-react-table#36]
当我鼠标滚动下滑一定距离后，在重新上滑到顶部，会出现thead和tbody中间有100px左右的空白。有遇到过吗

**Comment by 273403986** [comment]
art-virtual-blank top    <div class="art-virtual-blank top" style="height: 0px;"></div>   这个元素是做什么的

**Comment by 273403986** [comment]
art-virtual-blank top这个元素的top值会余留一个70px值

**Comment by shinima** [comment]
应该是虚拟滚动的bug，@273403986 能具体说一下复现的步骤么？   最好可以截个动图，谢谢啦

**Comment by 273403986** [comment]
![541B9978499D28968D80B7F345215923](https://user-images.githubusercontent.com/35244794/82188886-227fe900-9921-11ea-90e9-0debb9869182.png)

**Comment by 273403986** [comment]
这个70px是art-virtual-blank top这个元素上出现的，偶然出现，并不一定会出现。下拉滚动条不会出现这种情况。比方说鼠标往下滚动4，5下，在滚动上去，偶然就会出现这种情况。期望解决

**Comment by 806745845** [comment]
我也出现这种情况了....

**Comment by 806745845** [comment]
![image](https://user-images.githubusercontent.com/19372963/88248007-45889980-ccd2-11ea-87bd-263b56055d39.png)

**Comment by 806745845** [comment]
@shinima 

![GIF 2020-7-23 11-13-06](https://user-images.githubusercontent.com/19372963/88248962-8a61ff80-ccd5-11ea-9e89-2a91861a0300.gif)

**Comment by shinima** [comment]
确认下表格行元素 <tr /> 或者 表格元素 <table /> 有没有设置 margin/padding；如果有的话，将这些 padding/margin 都设置为 0。  我本地无法这个情况，暂时先关闭 issue 了
