### ISSUE TITLE
0.13.2 版本的 biz 模块引入错误

### ISSUE THREAD

**Issue by furybean** [alibaba/ali-react-table#37]
本地做了个最小重现案例，使用的 umi 的最新版本来使用 ali-react-table。

在 `import { applyTransforms, commonTransforms, SortItem } from 'ali-react-table/biz'` 会出现编译错误：

> error  in ./node_modules/ali-react-table/dist/ali-react-table-biz.esm.js  Module parse failed: Identifier 'treeMode' has already been declared (6:64) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders | import { a as isLeafNode, g as getTreeDepth, c as collectNodes, e as safeGetValue, d as safeGetCellProps, n as SpanManager, o as safeRenderHeader, p as STYLED_VERSION } from './chunks/ali-react-table-SpanManager-71d11259.esm.js'; | import styled__default from 'styled-components'; > import { f as flatMap, t as treeMode, a as treeMetaSymbol, b as treeMode, _ as __rest } from './chunks/ali-react-table-_tslib-1b7235e4.esm.js'; | import { Number_116, Number_216, Number_316, Number_416, Number_516, Number_616, Number_716, Number_816, Number_916, Information16, Column16, Download16 } from '@carbon/icons-react'; |   @ ./src/pages/index.tsx 6:0-54 9:32-47  @ ./src/.umi/core/routes.ts  @ ./src/.umi/umi.ts  @ multi ./src/.umi/umi.ts

做了另外两个测试：
1. 只引入 `import { ArtColumn, BaseTable } from 'ali-react-table'` ，不会报错。
2. 使用 0.13.1 版本引入 `ali-react-table/biz`，不会报错。

也就是说，这应该是 0.13.2 新引入的一个 Bug。

**Comment by shinima** [comment]
多谢提醒，我看了下本地打包出来的内容确实有问题。   

![image](https://user-images.githubusercontent.com/5550931/82398610-ce424980-9a85-11ea-8e8d-4bd0e8fb355d.png)

**Comment by shinima** [comment]
多谢提醒。0.13.2 触发了 rollup 的bug  https://github.com/rollup/rollup/pull/2737   我看下怎么绕过去

**Comment by shinima** [comment]
已经在 0.13.3 解决这个问题了

**Comment by furybean** [comment]
0.13.3 确认解决了。
