### ISSUE TITLE
能否提供冻结行（锁行）功能

### ISSUE THREAD

**Issue by hujinbo** [alibaba/ali-react-table#40]
看了文档目前只有锁列功能，能否提供冻结行功能。
场景：如表格底部最后一行为合计栏，一般需要冻结显示。

**Comment by shinima** [comment]
冻结行实现起来比较麻烦，这个需要再调研一下

**Comment by hujinbo** [comment]
好的，这个在一些统计类的表格还是比较常见的。
目前如果先自己实现，有啥思路可以参考吗。感谢！

**Comment by shinima** [comment]
> 目前如果先自己实现，有啥思路可以参考吗。感谢！

我想了下，暂时没什么好的想法……   冻结行 会涉及到左右侧锁列单元格尺寸同步和 虚拟滚动，导致实现会相当复杂，不知道有没有什么巧妙的办法

**Comment by hujinbo** [comment]
> > 目前如果先自己实现，有啥思路可以参考吗。感谢！
> 
> 我想了下，暂时没什么好的想法…… 冻结行 会涉及到左右侧锁列单元格尺寸同步和 虚拟滚动，导致实现会相当复杂，不知道有没有什么巧妙的办法

好的，谢谢
