### ISSUE TITLE
排序错误

### ISSUE THREAD

**Issue by LitterPig** [alibaba/ali-react-table#42]
![image](https://user-images.githubusercontent.com/19744021/85369363-92584380-b55f-11ea-84b9-f710f2b52d43.png)

**Comment by LitterPig** [comment]
里面如果有负数的情况，这个貌似就会出现

**Comment by shinima** [comment]
你把你的配置发一下吧      从图中看，这一列是按照字符串排序了，是不是在 getValue 中就进行了数字的格式化？   数字的格式化需要放在 column.render 中

**Comment by LitterPig** [comment]
正准备说这个问题，我后面放在render里面，进行百分比转化就可以。谢谢哈
