### ISSUE TITLE
0.13.5版本报错

### ISSUE THREAD

**Issue by wittech** [alibaba/ali-react-table#45]
编译0.13.5版本报错
* ./chunks/ali-react-table-_tslib-cbb871fd.esm.js in ./node_modules/ali-react-table/dist/ali-react-table-biz.esm.js

发现发布包里面的名称是：
ali-react-table-_tslib-8c532ff9.esm.js

**Comment by shinima** [comment]
多谢提醒，我检查一下

**Comment by shinima** [comment]
我试了一下，  0.13.5 发布的内容是没问题的

![image](https://user-images.githubusercontent.com/5550931/86517699-99375e00-be5d-11ea-848d-7da95de5798b.png)


我在 codesandbox 上也可以正常运行，你看下是不是你本地装了多个版本的问题？

codesandbox 链接：  https://codesandbox.io/s/ali-react-table-test-6c9yp
