### ISSUE TITLE
请教下，开启虚拟滚动的白屏问题

### ISSUE THREAD

**Issue by 806745845** [alibaba/ali-react-table#46]
版本：0.13.5
用的是交叉表 CrossTable
开启虚拟滚动白屏，（一大段的空白页）
把useVirtual={false}后，一切正常
看了文档后说是要：在虚拟滚动开启的情况下，需要使用 column.getSpanRect 来设定单元格合并的情况

这个就不知道要怎么设置了...

看了交叉表的文档，缺少了好多配置说明，，还有，expression这个可以用的有什么？

**Comment by shinima** [comment]
如果是使用 CrossTable 组件的话，默认就自带了单元格合并的功能，一般不需要再自己实现了。

> 看了交叉表的文档，缺少了好多配置说明，，还有，expression这个可以用的有什么？

能描述一下你想要的效果么，我不是很明白你想要达成什么样的效果？   CrossTable 是相当底层的组件，往往需要做很多定制工作的

**Comment by 806745845** [comment]
> 如果是使用 CrossTable 组件的话，默认就自带了单元格合并的功能，一般不需要再自己实现了。
> 白屏问题很可能是虚拟滚动的 bug，最好可以给一个可复用的示例…… 我本地的一些交叉表示例都是好的
> 
> > 看了交叉表的文档，缺少了好多配置说明，，还有，expression这个可以用的有什么？
> 
> 能描述一下你想要的效果么，我不是很明白你想要达成什么样的效果？ CrossTable 是相当底层的组件，往往需要做很多定制工作的

**Comment by 806745845** [comment]
已经解决了....原因是在CrossTable 组件外面套了一层div，给设置了height 跟overflow,，
把height 跟overflow,，设置在CrossTable 上问题就解决了
