### ISSUE TITLE
运行storybook报错了

### ISSUE THREAD

**Issue by earlymeme** [alibaba/ali-react-table#49]
ERROR in ./stories/pivot/pivot-utils.stories.tsx
Module not found: Error: Can't resolve 'core-js/modules/web.dom-collections.iterator' in 'E:\code\ali-react-table\stories\pivot'
 @ ./stories/pivot/pivot-utils.stories.tsx 15:0-54
 @ ./stories/pivot sync nonrecursive (?:pivot-utils\.stories\.tsx)$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in ./stories/pivot/MinimumPivotTableDesigner.tsx
Module not found: Error: Can't resolve 'core-js/modules/web.dom-collections.iterator' in 'E:\code\ali-react-table\stories\pivot'
 @ ./stories/pivot/MinimumPivotTableDesigner.tsx 11:0-54
 @ ./stories/pivot/pivot-utils.stories.tsx
 @ ./stories/pivot sync nonrecursive (?:pivot-utils\.stories\.tsx)$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

**Comment by shinima** [comment]
看起来像是缺少  core-js 这个库，我看看我本地清空 node_modules 能不能复现这个情况

**Comment by earlymeme** [comment]
> 看起来像是缺少 core-js 这个库 ~我看看我本地清空 node_modules 能不能复现这个情况~
> 似乎和 [zloirock/core-js#500](https://github.com/zloirock/core-js/issues/500) 这个有关系

我重新拉你的代码，重新npm install后还是不行:(

**Comment by shinima** [comment]
@earlymeme   `yarn add --dev core-js@3` 试试呢？

**Comment by earlymeme** [comment]
@shinima 又报这个了。。。
```
ERROR in ./src/biz/CustomColumnsDialog.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: E:\code\ali-react-table\src\biz\CustomColumnsDialog.tsx: Unexpected token (231:108)

  229 |     if (typeof STORYBOOK_REACT_CLASSES !== "undefined")
  230 |         // @ts-ignore
> 231 |         STORYBOOK_REACT_CLASSES["src/biz/CustomColumnsDialog.tsx#default.makeStyledDrawer"] = { docgenInfo: , default: .makeStyledDrawer.__docgenInfo, name: "default.makeStyledDrawer", path: "src/biz/CustomColumnsDialog.tsx#default.makeStyledDrawer" };
      |                                                                                                             ^
  232 | }
  233 | catch (__react_docgen_typescript_loader_error) { }
  234 | try {
    at Object._raise (E:\code\ali-react-table\node_modules\@babel\parser\src\parser\error.js:60:45)
    at Object.raiseWithData (E:\code\ali-react-table\node_modules\@babel\parser\src\parser\error.js:55:17)
    at Object.raise (E:\code\ali-react-table\node_modules\@babel\parser\src\parser\error.js:39:17)
    at Object.unexpected (E:\code\ali-react-table\node_modules\@babel\parser\src\parser\util.js:152:16)
```

**Comment by shinima** [comment]
@earlymeme  拉取一下最新代码，checkout enhance-doc 分支，这个分支我本地是 ok 的

**Comment by earlymeme** [comment]
可以了
