### ISSUE TITLE
请教一个源码问题

### ISSUE THREAD

**Issue by earlymeme** [alibaba/ali-react-table#50]
大佬，我有个源码问题一直没想明白
 #就是在componentDidMount的时候，执行initSubscriptions，里面的mainBody是绑定的emptyTable的那个Classes.TableBody （https://github.com/alibaba/ali-react-table/blob/v0.13.6/src/base-table/table.tsx#L414 ），
数据渲染后，mainBody引用的dom会更新成这个dom ( https://github.com/alibaba/ali-react-table/blob/v0.13.6/src/base-table/table.tsx#L429 )
为什么在VisibleClipRectObservable这个https://github.com/alibaba/ali-react-table/blob/v0.13.6/src/base-table/helpers/VisibleClipRectObservable.ts#L46 里target可以拿到这个新的dom？
> 我现在正在换成vue实现一遍

**Comment by shinima** [comment]
因为 React 虚拟的 DOM 机制，虽然虚拟 dom 有发生变化，底下的 HTMLDivElement 还是同一个。

**Comment by earlymeme** [comment]
感谢！！！
