### ISSUE TITLE
表格可以支持拖动排序吗？感觉这个功能还是比较实用的。

### ISSUE THREAD

**Issue by sunflower-li** [alibaba/ali-react-table#52]

**Comment by shinima** [comment]
目前还暂时不支持，后续会考虑加上，目前在优化表格的 DOM 结构，可能要等一段时间了。

**Comment by sunflower-li** [comment]
> 目前还暂时不支持，后续会考虑加上，目前在优化表格的 DOM 结构，可能要等一段

**Comment by shinima** [comment]
拖动排序要考虑虚拟滚动的话 太复杂了，工作比较忙，短时间内不会考虑实现了。
