### ISSUE TITLE
希望树状表格 支持自定义parent_id名称更好支持树结构直接渲染

### ISSUE THREAD

**Issue by zjcwill** [alibaba/ali-react-table#59]
现在只提供了拍平数据转换支持自定义`parent_id` 字段构建出树状结构，已有的树结构因为`parent_id`不是`children`导致无法直接使用源数据渲染，希望支持一下`makeTreeModeTransform`添加`parentId`

**Comment by shinima** [comment]
给 makeTreeModeTransform 添加一个额外的配置，支持 children 之外的字段名是没问题的。

不过很多其他的 API 都有 “children 存放了子节点” 的约定，如果只给 `makeTreeModeTransform` 加上的话 parentId 配置的，API 之间会存在一定程度的不一致。这个我再考虑下。

**Comment by shinima** [comment]
给 makeTreeModeTransform 添加一个额外的配置，支持 children 之外的字段名是没问题的。

不过很多其他的 API 都有 “children 存放了子节点” 的约定，如果只给 `makeTreeModeTransform` 加上的话 parentId 配置的，API 之间会存在一定程度的不一致。这个我再考虑下。

**Comment by zjcwill** [comment]
可以参考这个写法 加到column里 ，感觉就会解决你说那个API不一致的问题

https://shine.wiki/1.5.x/cn/components/Table

```js
const columns = [
  { title: 'Name', render: d => `${d.firstName} ${d.lastName}`, width: 300, treeColumnsName: 'children' },
  { title: 'Country', render: 'country' },
  { title: 'Position', render: 'position' },
  { title: 'Office', render: 'office' },
]
```

**Comment by shinima** [comment]
很多地方已经约定了 children 用来表示子节点数组，这里不打算进行拓展了。
