### ISSUE TITLE
横向虚拟滚动的时候回出现表头和内容无法对齐的情况 滑动结束之后会对齐

### ISSUE THREAD

**Issue by 0408jiahuicao** [alibaba/ali-react-table#61]
横向虚拟滚动的时候回出现表头和内容无法对齐的情况 滑动结束之后会对齐

**Comment by 0408jiahuicao** [comment]
会有抖动的感觉

**Comment by 0408jiahuicao** [comment]
> v0.x 中表格表头上 设置了 overflow: hidden，确实会有 抖动的情况。
> v1.0 （目前还是 beta 版本）中表头用了 overflow: auto，但是通过 CSS 隐藏了滚动条，这个情况应该会好一些，等 1.0 正式发布之后再看下吧。

期待😍😍😍

**Comment by shinima** [comment]
@0408jiahuicao   几天前 v1.0 已经发布了，你更新下版本号就可以了

**Comment by shinima** [comment]
在 1.0 中横向滚动已经优化过了，有问题的话可以重新打开这个 issue
