### ISSUE TITLE
有没有什么api可以更改表格的字体呢，或者css变量

### ISSUE THREAD

**Issue by aierweisi** [alibaba/ali-react-table#63]
我想把表格默认的12px更改为14px，还请指教一下，谢谢

**Comment by shinima** [comment]
覆盖一下默认的 CSS 样式就好了， 可以通过 styled-components，也可以通过引入 CSS 文件。

```
.art-table {
  font-size: 14px;
}
```

**Comment by aierweisi** [comment]
> 覆盖一下默认的 CSS 样式就好了， 可以通过 styled-components，也可以通过引入 CSS 文件。
> 
> ```
> .art-table {
>   font-size: 14px;
> }
> ```

好的，谢谢🙏
