### ISSUE TITLE
扩展一个筛选功能遇到的问题

### ISSUE THREAD

**Issue by ChipmunkJerry** [alibaba/ali-react-table#65]
由于开发时间比较紧张所以没能仔细阅读例子以及源码…
十分抱歉打扰，希望可以得到你们的帮助。

功能：表头添加筛选图标，点击图标显示筛选弹窗
[效果如antd Table自定义筛选](https://ant.design/components/table-cn/#components-table-demo-custom-filter-panel)
【思考】首先该如何写一个表头渲染，用来增加筛选按钮，弹框和功能？
以排序为例，发现相关api有features applyTransforms makeSortTransform
【疑问】可以通过写一个类似makeSortTransform方法来实现筛选吗？
clumns该如何处理?
safeRenderHeader(col)好像也取不到(ಥ﹏ಥ)

我正在开始我的尝试，希望能得到你们的帮助得以启发

**Comment by ChipmunkJerry** [comment]
oh我暂时找到了internals  感动！我继续尝试

**Comment by shinima** [comment]
> 可以通过写一个类似makeSortTransform方法来实现筛选吗？

可以的

> clumns该如何处理?

一般来说 需要自行对 columns 进行遍历；ali-react-table 也提供了 traverseColumn 来辅助对 columns 的遍历操作

**Comment by shinima** [comment]
以下代码仅供思路参考：

```js
function makeFilterTransform({ filterState, onChangeFilterState }) {
  return ({ columns, dataSource }) => {
    // 根据 filterState 来过滤数据源
    const filteredDataSource = dataSource.filter((row) => test(filterState, row))

    // 遍历 columns，在每一列的表头生成一个 过滤的图标，点击图表弹出过滤面板
    // 注意 columns 是一个嵌套的结构，一般情况下得用递归来进行遍历
    const nextColumns = columns.map((col) => {
      if (!col.features?.showFilter){
        // 只有 features.showFilter 的列才支持过滤
        return col
      }
      const name = col.name
      return {
        ...col,
        title: (
          <div>
            {name}
            <FilterIcon
              onClick={() => {
                showFilterPopup(col.code)
              }}
            />
          </div>
        ),
      }
    })

    return { dataSource: filteredDataSource, columns: nextColumns }
  }
}

// 在使用时……

const [filterState, onChangeFilterState] = useState([])

const renderData = applyTransforms(
  { dataSource, columns },
  makeFilterTransform({ filterState, onChangeFilterState }),
  makeSortTransform(...)
)
```

**Comment by ChipmunkJerry** [comment]
非常感谢你的回答，功能可以很好的实现

**Comment by shinima** [comment]
@ChipmunkJerry  我写了个 demo 你可以参考下： [示例-表格交互-筛选--筛选](https://ali-react-table.js.org/?path=/story/%E7%A4%BA%E4%BE%8B-%E8%A1%A8%E6%A0%BC%E4%BA%A4%E4%BA%92-%E7%AD%9B%E9%80%89--%E7%AD%9B%E9%80%89)

实现起来还是比较麻烦的，代码在[这里](https://github.com/alibaba/ali-react-table/blob/6b42430ffc554a51474f69f9bbeedce083774b88/stories/examples/interactions/filter.stories.tsx)

**Comment by ChipmunkJerry** [comment]
嗯嗯感谢，很详细，值筛选这个也很棒我都没想到
applyTransforms这种拓展方式挺好用的，再次感谢
