### ISSUE TITLE
树状表格多选可以通过哪个方法实现，官方文档没有看到

### ISSUE THREAD

**Issue by zjcwill** [alibaba/ali-react-table#66]
![image](https://user-images.githubusercontent.com/22348984/91154232-ddbfd700-e6f3-11ea-8c4d-bdfde44b3d60.png)
类似ant desgin  这种，是很常见的功能

**Comment by shinima** [comment]
这个可以在树状模式的基础上修改实现，我过会儿写个 demo

**Comment by shinima** [comment]
我写了个 demo，你可以参考一下相关的代码。

在线 demo：[示例-表格交互-单选与多选--树形选择](https://ali-react-table.js.org/?path=/story/%E7%A4%BA%E4%BE%8B-%E8%A1%A8%E6%A0%BC%E4%BA%A4%E4%BA%92-%E5%8D%95%E9%80%89%E4%B8%8E%E5%A4%9A%E9%80%89--%E6%A0%91%E5%BD%A2%E9%80%89%E6%8B%A9)


示例源码：  https://github.com/alibaba/ali-react-table/blob/0d92db89b6ed654c837d511eaca508044c4dae80/stories/examples/interactions/select.stories.tsx#L238-L294

树状数据处理工具：
https://github.com/alibaba/ali-react-table/blob/0d92db89b6ed654c837d511eaca508044c4dae80/stories/examples/interactions/makeTreeDataHelper.tsx

**Comment by zjcwill** [comment]
> 示例-表格交互-单选与多选--树形选择

感觉 demo补充

**Comment by zjcwill** [comment]
我试了下   现在组件里没有暴露这个方法  `makeTreeSelectTransform `  版本为1.01
![image](https://user-images.githubusercontent.com/22348984/91273171-6ea7b880-e7af-11ea-909a-f56a8d035695.png)

**Comment by shinima** [comment]
> 我试了下 现在组件里没有暴露这个方法 makeTreeSelectTransform 版本为1.0

确实没有暴露，你先直接 copy 一下代码吧。

ali-react-table 的定位是灵活的、高性能底层表格组件，像 makeTreeSelectTransform 这样的 API 可以在上层定制得到的话，ali-react-table 就不会再暴露这些 API 了。
