### ISSUE TITLE
左侧锁列，滚动到最右侧有这种样式问题，有办法解决吗

### ISSUE THREAD

**Issue by aierweisi** [alibaba/ali-react-table#68]
![image](https://user-images.githubusercontent.com/33406910/91251680-8884d380-e78e-11ea-8419-007c25c3da61.png)

**Comment by shinima** [comment]
应该是「最右边的单元格中的内容超出单元格范围」导致的问题，给 最后一列设置一个比较大的宽度试试呢？   也可以通过 CSS 设置 overflow=hidden

**Comment by aierweisi** [comment]
> 应该是「最右边的单元格中的内容超出单元格范围」导致的问题，给 最后一列设置一个比较大的宽度试试呢？ 也可以通过 CSS 设置 overflow=hidden

这样确实能解决，谢谢
