### ISSUE TITLE
0.14 版本在 Chrome49 中的兼容性问题

### ISSUE THREAD

**Issue by ChipmunkJerry** [alibaba/ali-react-table#69]
实在抱歉又来打扰

因为需要兼容chrome49，期初看到chrome49不支持 sticky没很在意，本以为只是会没有吸顶效果，可以用fixed父容器替代……

但是真正运行在Chrome49以后发现报错：
在updateItemStore()
 queryAll(...).forEach is not a function
难受啊 是否能不用sticky……

希望能得到你的帮助

**Comment by shinima** [comment]
好的，这个是因为  NodeList#forEach 在 chrome 51 之后才能用导致，我改进一下写法

相关资料：  https://developer.mozilla.org/zh-CN/docs/Web/API/NodeList/forEach

**Comment by ChipmunkJerry** [comment]
不想放弃使用o(╥﹏╥)o

你们有做兼容的计划么

或者有什么代替方案可以分享一下吗

**Comment by Kehao** [comment]
主要是支持WinXP的最高版本是chrome 49, to B的好多客户装的是WinXP～

**Comment by shinima** [comment]
我明天更新一下 0.14 版本吧，0.14 处理之后也许可以兼容 chrome49

**Comment by foolyoghurt** [comment]
Tob 场景下 XP 就没必要支持了吧，为了兼容性，增加代码的可维护性，以后包袱越背越重。我觉得 ali-react-table 的定位就应该是一个现代版本的 Table，轻量纯粹一点

**Comment by ChipmunkJerry** [comment]
toB暂时没法抛弃XP，金融硬件设备很多还停留在XP，业务流程中任意一环崩溃又都不行……所以还是只能兼容

如果违背了原本定位不能做兼容的话能够理解，但还是很感谢作者愿意帮助

**Comment by shinima** [comment]
试一下 0.14.2 版本，这个版本去掉了 NodeList#forEach 的使用，应该可以跑在 chrome49 上。

1.0 之后的版本必须得在 chrome 56+ 中才能使用

**Comment by coingpaic** [comment]
NodeList#forEach的问题通过加polyfill解决了。现在不兼容49，主要是sticky不兼容。

**Comment by shinima** [comment]
> 现在不兼容49，主要是sticky不兼容。

sticky 不兼容暂时不管了，没有简单的办法做到兼容。
