### ISSUE TITLE
我明天更新一下 0.14 版本吧，0.14 处理之后也许可以兼容 chrome49

### ISSUE THREAD

**Issue by coingpaic** [alibaba/ali-react-table#70]
我明天更新一下 0.14 版本吧，0.14 处理之后也许可以兼容 chrome49

_Originally posted by @shinima in https://github.com/alibaba/ali-react-table/issues/69#issuecomment-682036309_

请问做了兼容chrome49的处理了吗？我们也是49，主要问题是不兼容sticky.谢谢！

**Comment by shinima** [comment]
最近几天会修改 0.14 版本

和 #69 重复了，以 #69 为准吧
