### ISSUE TITLE
throttledWindowResize$位置报错

### ISSUE THREAD

**Issue by ChipmunkJerry** [alibaba/ali-react-table#72]
你好，可以看一下可能导致这个方法错误的原因吗

报错指向 `// 使用 defer 避免过早引用 window，导致在 SSR 场景下报错
export const throttledWindowResize$ = defer(() =>
  fromEvent(window, 'resize').pipe(throttleTime(150, asyncScheduler, { leading: true, trailing: true })),
)`

报错信息：Uncaught TypeError: Object(...) is not a funtion

引用在一个新的工程，不知道是哪个配置不对还是其他代码影响，排查不出问题。

**Comment by Jiangwenzhe** [comment]
我也遇到了这个问题，可以问一下你是怎么解决的吗？

**Comment by Jiangwenzhe** [comment]
我也遇到了一样的问题，请问您的解决方法是什么？
