### ISSUE TITLE
表格宽度自适应

### ISSUE THREAD

**Issue by hzhijun** [alibaba/ali-react-table#75]
我们是做 BI 统计系统的，为了看数据方便，需要数据尽量能一屏显示（表格紧凑），列宽如果我们自己设置的话，可能有的列会出现空余宽度的情况，有的列可能就显示不全。

**Comment by hzhijun** [comment]
还有一种情况是，如果设置了列宽，但实际数据超过了指定宽度，让数据自动换行会好一些

**Comment by shinima** [comment]
目前表格是以「行高自适应、列宽固定」的方式来开发的，不支持列宽的自适应。 

> 列宽如果我们自己设置的话，可能有的列会出现空余宽度的情况，有的列可能就显示不全。

想实现宽度自适应的话，可能在上层进行处理会比较好（比如在 父组件 didMount 中获取每一列的渲染所需要的实际宽度，这个我在本地尝试一下）

> 设置了列宽，但实际数据超过了指定宽度，让数据自动换行会好一些

这个应该可以通过 CSS 来进行设置了，相关的属性：overflow / text-overflow / word-wrap / overflow-wrap（比较多，我不太记得清是哪个了）

**Comment by hzhijun** [comment]
好的，辛苦了，关于在 antd-pro 中，表头无法悬浮的情况，你在本地有复现吗？

**Comment by shinima** [comment]
> 表头无法悬浮的情况，你在本地有复现

复现了， ant-layout 上设置了 overflow，导致表格吸顶失效了

![image](https://user-images.githubusercontent.com/5550931/93737599-31034780-fc16-11ea-8a38-38253c15d7e6.png)

**Comment by shinima** [comment]
> 列宽如果我们自己设置的话，可能有的列会出现空余宽度的情况，有的列可能就显示不全

这几天我在本地尝试了实现…  先让表格内容渲染一遍，然后读取单元格内容的实际渲染宽度，这样可以做到「自适应列宽」  。 这意味着「表格宽度自适应」需要频繁读取 DOM 中的状态，表格单元格较多时 性能很差，与一些其他表格特性也不兼容。

这两天我会发布 v1.2，里面提供了 useAutoWidthTransform 可以实现自适应列宽。

**Comment by shinima** [comment]
自适应列宽可以参考这个 [demo](https://ali-react-table.js.org/?path=/story/%E8%A1%A8%E6%A0%BC-%E5%B8%B8%E7%94%A8%E5%8A%9F%E8%83%BD%E7%A4%BA%E4%BE%8B--%E8%87%AA%E9%80%82%E5%BA%94%E5%88%97%E5%AE%BD-demo)，相关代码在[这里](https://github.com/alibaba/ali-react-table/blob/0582ed57c2b3c33f8b6157df49b582c1edf2fee1/stories/table/transforms-examples.stories.tsx#L499-L555) .

**Comment by hzhijun** [comment]
好的  感谢老哥
