### ISSUE TITLE
开启虚拟滚动后，表格拉到底部会存在一直上下抖动的情况

### ISSUE THREAD

**Issue by aierweisi** [alibaba/ali-react-table#76]
请问下，这个有办法修复吗

**Comment by shinima** [comment]
确认下表格行 <tr /> 或者 表格元素  <table /> 有没有设置上下的 margin/padding；如果有的话，将这些 padding/margin 都设置为 0

然后能否提供一下相关的代码或示例，这个我得复现才能修父

**Comment by aierweisi** [comment]
> 确认下表格行 `<tr />` 或者 表格元素 `<table />` 有没有设置 margin/padding；如果有的话，将这些 padding/margin 都设置为 0。
> 
> 然后能否提供一下相关的代码或示例，这个我得复现才能修复

erp.test1.zhaojiafang.com
账号：ceshizh1  密码： 123456
订单打印页面，数据切换成100条，切换分页，往下拉，可以复现

**Comment by shinima** [comment]
我试了一下，除了滚动条有点不太稳定之外，并没有出现上下抖动的情况…

**Comment by aierweisi** [comment]
> 我试了一下，除了滚动条有点不太稳定之外，并没有出现上下抖动的情况…

方便加一下钉钉或者其他的联系方式吗？我录视频给你看，麻烦了

**Comment by shinima** [comment]
@aierweisi   我的钉钉号  feichao93

**Comment by shinima** [comment]
在 ef285fcd37db38e3f08ca6f70b9771f0764dbb00 中已修复
v2.0.4 之后应该没问题了
