### ISSUE TITLE
以后是否支持可展开行

### ISSUE THREAD

**Issue by 569202812** [alibaba/ali-react-table#81]

**Comment by shinima** [comment]
会的。  已经在开发了，敬请期待

https://github.com/alibaba/ali-react-table/blob/35f57072afbc391bab69507be58ba64ecf56a547/src/pipeline/features/index.ts#L3-L4

**Comment by 569202812** [comment]
> 会的。 已经在开发了，敬请期待
> 
> https://github.com/alibaba/ali-react-table/blob/35f57072afbc391bab69507be58ba64ecf56a547/src/pipeline/features/index.ts#L3-L4

收到
