### ISSUE TITLE
antd导致表格吸顶以及css无效

### ISSUE THREAD

**Issue by zhanghanduo** [alibaba/ali-react-table#83]
你好作为新手小白不好意思问一下，我现在用的是antd的一系列组件，包括Layout，在里面创建table的时候表格吸顶无效，而且设置长宽也都不可以，应该是antd override了css吧？请问有什么办法可以解决这个问题吗？比如手动提取antd的本地css进行修改，还是我得换一个framework，比如material-UI或者自己写？多谢！

**Comment by shinima** [comment]
这个一般是因为 Table 上层的某个元素出现了 overflow=auto 或是 overflow=hidden 的情况，这个时候放在 Table 上的 sticky position 是不会生效的。
sticky 的生效规则有点绕，具体可以看下这些资料：
https://developer.mozilla.org/zh-CN/docs/Web/CSS/position#Sticky_positioning   https://www.zhangxinxu.com/wordpress/2018/12/css-position-sticky/

一般来说，你可以先在 浏览器 inspector 中把表格上层的 overflow=hidden/auto 都去掉试试（特别注意一些容器组件，很可能会带上 overflow 样式），这样表格吸顶应该就能生效了。

**Comment by sunwenli** [comment]
这个吸顶功能在 antd pro 里确实是不生效 😹

**Comment by shinima** [comment]
这个 antd pro 样式引起的问题，表格组件没什么好办法来解决这个问题

**Comment by sunwenli** [comment]
> 这个是 antd pro 样式引起的问题，表格组件没啥办法来解决这个问题

我把 Table 的父组件里有 overflow 属性的挨个都给勾掉，能吸顶了。😂

**Comment by sunwenli** [comment]
在用到 这个 table组件的界面通过 dom 改样式，暂时能解决
modifySectionLayout = (tagName) => {
    // tagName = "section"
    let sectionDom = document.getElementsByTagName(tagName);
    if (sectionDom && sectionDom.length > 1) {
      let tableSection = sectionDom[1]
      ReactDOM.findDOMNode(tableSection).style.overflowX = "visible";
    }
  }
