### ISSUE TITLE
单元格渲染优化

### ISSUE THREAD

**Issue by 154305** [alibaba/ali-react-table#84]
目前很多场景需要编辑单元格，但是页面大量的单元格在编辑的时候会造成卡顿现象，能否提供提个跟antd-table对于单元格控制渲染的方法shouldCellUpdate

**Comment by shinima** [comment]
我看下 shouldCellUpdate 是否需要

你先设置一下 useVirtual={true} 试试呢，开启虚拟滚动后 同时渲染的单元格数量应该是有限的，看下性能是否可以接受。

**Comment by lucaslz2020** [comment]
我感觉确实需要这个，不然很卡顿，特别是变成qiankun子系统。独立运行稍微好一点点
