### ISSUE TITLE
请问能支持 表格数据选中（类似于 excel 的那种，拖拉手柄选择一个区块）吗

### ISSUE THREAD

**Issue by tobemaster56** [alibaba/ali-react-table#85]

**Comment by shinima** [comment]
单个单元格的选中比较容易实现，给选中 td 元素设置一下 border 样式即可；
多选或是框选 实现起来较为复杂，目前暂不考虑该功能。 （需要框选功能的话，推荐找一些类 excel 的表格组件，像 ali-react-table 这样基于 `<table />` / `<tr / >` / `<td />` 的实现方式并不是很适合用来实现类 excel 表格）
