### ISSUE TITLE
透视表支持排序和筛选吗？

### ISSUE THREAD

**Issue by GannonSun** [alibaba/ali-react-table#87]
好像pipeline不支持透视表哎？

**Comment by shinima** [comment]
应该是支持的，开启排序比较麻烦一些，我先在本地在验证一下。

文档中我还没写，本地验证好了之后 我补充一下文档。

**Comment by GannonSun** [comment]
> 应该是支持的，开启排序比较麻烦一些，我先在本地在验证一下。
> 
> 文档中我还没写，本地验证好了之后 我补充一下文档。

好的，等待大佬

**Comment by PathFun** [comment]
希望可以支持

**Comment by shinima** [comment]
已支持   https://ali-react-table.js.org/docs/pivot/cross-table#%E4%BA%A4%E5%8F%89%E8%A1%A8%E5%AE%9A%E5%88%B6

**Comment by feEden** [comment]
> 已支持 https://ali-react-table.js.org/docs/pivot/cross-table#%E4%BA%A4%E5%8F%89%E8%A1%A8%E5%AE%9A%E5%88%B6

交叉表点击排序，左树 数据展示错乱
https://codesandbox.io/s/nervous-jones-e0o15n?file=/src/App.tsx
