### ISSUE TITLE
滚动不同步

### ISSUE THREAD

**Issue by Love-YGX-and-D** [alibaba/ali-react-table#88]
简易透视表中，左右滚动时， 头部和下面的内容滚动不同步，会有一个小小的延迟

**Comment by shinima** [comment]
嗯，目前确实存在小小的延迟。   因为表格 header 和 body 是处于两个不同的 div 中，两个 div 有各自的滚动条（表头上的滚动条被隐藏了起来），同步滚动偏移量的时候存在一定延迟。
