### ISSUE TITLE
大佬，能否增加列拖动功能

### ISSUE THREAD

**Issue by ab2976818** [alibaba/ali-react-table#89]
其它功能已经很强大，希望能增加列宽拖动功能,感谢

**Comment by shinima** [comment]
其实目前还是有这个功能的  
https://ali-react-table.js.org/v1/?path=/story/%E8%A1%A8%E6%A0%BC-%E5%B8%B8%E7%94%A8%E5%8A%9F%E8%83%BD%E7%A4%BA%E4%BE%8B--%E6%8B%96%E6%8B%BD%E8%B0%83%E6%95%B4%E5%88%97%E5%AE%BD

不过这个 列拖动功能 和 高性能 的出发点是冲突的（高性能是为了展示更多的列，但在列多的时候 拖动功能基本上没什么用），所以 v2 版本我没把 拖动调整列宽加到拓展功能中。  后面要不要加上这个我还得再想想 🤔
