### ISSUE TITLE
TreeTable 展开收起icon 希望 可自定义

### ISSUE THREAD

**Issue by zhiaiing** [alibaba/ali-react-table#94]
TreeTable 展开收起icon 希望 可自定义

**Comment by shinima** [comment]
😂  这个符号用到的地方相当多，暂时还没什么时间改
不过你可以在上层自己实现一个 treeMode，明天我写个 demo

**Comment by shinima** [comment]
@zhiaiing   你可以按照这个文件改成你想要的树状模式，里面选项较多，用不到的选项你可以把它删掉

https://github.com/alibaba/ali-react-table/blob/8d0809c185bbac300fcf661bd7f8750b54e4180a/packages/ali-react-table/src/pipeline/features/treeMode.tsx

**Comment by zhiaiing** [comment]
好的， 多谢
