### ISSUE TITLE
希望 components 可以暴露更多的东西 如 table body tr

### ISSUE THREAD

**Issue by zhiaiing** [alibaba/ali-react-table#95]
希望 components 可以暴露更多的东西 如 table body tr
这样的话就可以实现行拖拽

**Comment by zhiaiing** [comment]
如果自己改源码的话是不是改ali-react-table-master/packages/ali-react-table/src/base-table/table.tsx 里面的代码就行
<img width="1157" alt="WechatIMG510" src="https://user-images.githubusercontent.com/15857315/98492655-7f76af00-2273-11eb-9361-81e83587b180.png">

**Comment by shinima** [comment]
嗯，这个我也有想过。     不过最近挺长一段时间 我都没碰到过需要拖拽来进行排序的场景，所以暂时每加。

**Comment by lucaslz2020** [comment]
表格列拖拽这个还是有场景的, 可伸缩列这个功能点用户很需要.

**Comment by cccRaim** [comment]
场景还是有的，这是体验提升中一个比较重要的一部分

**Comment by liuweiGL** [comment]
## 使用场景

需要在 cell 外面包裹一个 `RowContextProvider` 让子组件消费。

## 目前存在的问题

因为无法自定义 tr，只能在 render 里面渲染 `RowContextProvider`，在数据量大而又不希望使用虚拟滚动的时候性能影响大。

## 期望

能把 tr 渲染接口暴露出来。

**Comment by shinima** [comment]
@liuweiGL  嗯   RowContextProvider 这个情况我也遇到了，这两天我抽空加一下
