### ISSUE TITLE
交叉表可以像普通表一样自定义固定列吗

### ISSUE THREAD

**Issue by Zmoshou** [alibaba/ali-react-table#98]
你好，目前我看了下，如果是较差表 好像是左边维度的列会默认固定的  请问支持自定义固定多少列吗

**Comment by shinima** [comment]
目前暂不开放，交叉表中改变固定的列的情况非常少见.

**Comment by kellywang1314** [comment]
你好，请问下透视表目前支持给列增加色条吗

**Comment by shinima** [comment]
@kellywang1314 通过下面的方式可以指定每个单元格的 props.style

```js
<CrossTable getCellProps={(arg1, arg2) => return { style: {} } }} />
```

getCellProps 的参数如下图：

![image](https://user-images.githubusercontent.com/5550931/103849637-378fcf00-50e0-11eb-9787-8ad2dffa2977.png)
